@extends('layouts.app')

@section('title', 'Water Tracking | Balance+')

@section('content')
<section class="py-16">
    <div class="container mx-auto px-4 max-w-6xl">

        <!-- Header -->
        <div class="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-12">
            <div>
                <h2 class="text-5xl font-black text-slate-900 tracking-tight mb-4">Water Tracking</h2>
                <p class="text-slate-500 font-medium">Stay hydrated and monitor your daily water intake</p>
            </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-12 gap-10">

            <!-- Main Tracking Area -->
            <div class="lg:col-span-8 space-y-8">

                <!-- Progress Card -->
                <div class="bg-white rounded-[2rem] border border-slate-100 shadow-sm p-10">
                    <div class="text-center mb-10">
                        <div class="flex items-baseline justify-center gap-2 mb-3">
                            <span id="waterCount" class="text-7xl font-black text-primary tracking-tighter">0</span>
                            <span class="text-slate-300 text-3xl font-bold">/8</span>
                        </div>
                        <p class="text-xs font-black text-primary uppercase tracking-[0.3em]">Cups Consumed</p>
                    </div>

                    <!-- Progress Bar -->
                    <div class="mb-10">
                        <div class="w-full h-3 bg-slate-100 rounded-full overflow-hidden">
                            <div id="progressBar" class="h-full bg-primary rounded-full transition-all duration-700" style="width: 0%"></div>
                        </div>
                        <p class="text-[10px] text-slate-400 mt-3 font-medium text-center">
                            <span id="progressText">Start your day with a glass of water! 💧</span>
                        </p>
                    </div>

                    <!-- Cups Grid -->
                    <div class="grid grid-cols-4 sm:grid-cols-8 gap-4 mb-8" id="cupsContainer">
                        <!-- Cups will be generated by JavaScript -->
                    </div>

                    <!-- Quick Actions -->
                    <div class="flex gap-4 justify-center pt-6 border-t border-slate-100">
                        <button onclick="resetWater()" class="px-6 py-3 bg-slate-100 text-slate-600 rounded-2xl font-bold text-xs uppercase tracking-widest hover:bg-slate-200 transition-all flex items-center gap-2">
                            <i class="fa-solid fa-rotate-left"></i>
                            Reset
                        </button>
                        <button onclick="completeGoal()" class="px-6 py-3 bg-primary text-white rounded-2xl font-bold text-xs uppercase tracking-widest hover:bg-primaryDark shadow-lg shadow-primary/20 transition-all flex items-center gap-2">
                            <i class="fa-solid fa-check"></i>
                            Complete Goal
                        </button>
                    </div>
                </div>

            </div>

            <!-- Sidebar -->
            <div class="lg:col-span-4 space-y-6">

                <!-- Today's Stats -->
                <div class="bg-white rounded-[2rem] border border-slate-100 shadow-sm p-8">
                    <h3 class="text-lg font-black text-slate-800 mb-6">Today's Stats</h3>
                    <div class="space-y-5">
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-3">
                                <div class="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center">
                                    <i class="fa-solid fa-fire-flame-curved text-primary"></i>
                                </div>
                                <div>
                                    <p class="text-xs text-slate-400 font-medium">Daily Goal</p>
                                    <p class="text-lg font-black text-slate-800">2L</p>
                                </div>
                            </div>
                        </div>
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-3">
                                <div class="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center">
                                    <i class="fa-solid fa-percent text-blue-500"></i>
                                </div>
                                <div>
                                    <p class="text-xs text-slate-400 font-medium">Achievement</p>
                                    <p class="text-lg font-black text-slate-800" id="achievementCount">0%</p>
                                </div>
                            </div>
                        </div>
                        <div class="flex items-center justify-between">
                            <div class="flex items-center gap-3">
                                <div class="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center">
                                    <i class="fa-solid fa-calendar-day text-emerald-500"></i>
                                </div>
                                <div>
                                    <p class="text-xs text-slate-400 font-medium">Streak</p>
                                    <p class="text-lg font-black text-slate-800" id="streakCount">0 days</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Hydration Tips -->
                <div class="bg-gradient-to-br from-primary to-primaryDark rounded-[2rem] p-8 text-white shadow-lg">
                    <div class="w-12 h-12 bg-white/20 rounded-2xl flex items-center justify-center mb-6">
                        <i class="fa-solid fa-lightbulb text-2xl"></i>
                    </div>
                    <h3 class="text-lg font-black mb-4">Hydration Tips</h3>
                    <ul class="space-y-3 text-sm opacity-90">
                        <li class="flex items-start gap-3">
                            <i class="fa-solid fa-check mt-0.5"></i>
                            <span>Drink a glass of water when you wake up</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <i class="fa-solid fa-check mt-0.5"></i>
                            <span>Set reminders every 2 hours</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <i class="fa-solid fa-check mt-0.5"></i>
                            <span>Keep a water bottle nearby</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <i class="fa-solid fa-check mt-0.5"></i>
                            <span>Drink before you feel thirsty</span>
                        </li>
                    </ul>
                </div>

            </div>

        </div>

    </div>
</section>

<script>
document.addEventListener('DOMContentLoaded', () => {
    const cupsContainer = document.getElementById('cupsContainer');
    const waterCountText = document.getElementById('waterCount');
    const progressBar = document.getElementById('progressBar');
    const progressText = document.getElementById('progressText');
    const achievementCount = document.getElementById('achievementCount');

    let activeCups = 0;
    const dailyGoal = 8;

    // Load saved progress from localStorage
    const savedProgress = localStorage.getItem('waterProgress');
    const savedDate = localStorage.getItem('waterProgressDate');
    const today = new Date().toDateString();

    if (savedProgress && savedDate === today) {
        activeCups = parseInt(savedProgress);
    } else {
        activeCups = 0;
        localStorage.setItem('waterProgressDate', today);
    }

    // Create cups
    function createCups() {
        cupsContainer.innerHTML = '';
        for (let i = 0; i < dailyGoal; i++) {
            const cup = document.createElement('div');
            cup.className = "cup cursor-pointer relative group flex flex-col items-center";
            cup.innerHTML = `
                <div class="water-vessel w-full aspect-[2/3] border-2 border-slate-200 rounded-b-2xl rounded-t-sm relative overflow-hidden transition-all duration-300 bg-slate-50/50 group-hover:border-primary">
                    <div class="water-fill absolute bottom-0 left-0 w-full h-0 bg-primary transition-all duration-500"></div>
                    <div class="water-surface absolute bottom-0 left-0 w-full h-1 bg-white/30 opacity-0 transition-opacity"></div>
                </div>
                <span class="text-[8px] font-black text-slate-300 mt-2 uppercase tracking-tighter">${i + 1}</span>
            `;

            cup.onclick = () => {
                activeCups = (i + 1 === activeCups) ? i : i + 1;
                updateWaterUI();
                saveProgress();
            };
            cupsContainer.appendChild(cup);
        }
        updateWaterUI();
    }

    function updateWaterUI() {
        const vessels = document.querySelectorAll('.water-vessel');
        const fills = document.querySelectorAll('.water-fill');
        const surfaces = document.querySelectorAll('.water-surface');

        vessels.forEach((vessel, i) => {
            if (i < activeCups) {
                setTimeout(() => {
                    fills[i].style.height = "100%";
                    vessel.style.borderColor = "#0B6B7A";
                    vessel.style.boxShadow = "0 10px 15px -3px rgba(11, 107, 122, 0.2)";
                    surfaces[i].style.opacity = "1";
                }, i * 50);
            } else {
                fills[i].style.height = "0%";
                vessel.style.borderColor = "#E2E8F0";
                vessel.style.boxShadow = "none";
                surfaces[i].style.opacity = "0";
            }
        });

        waterCountText.innerText = activeCups;

        const percentage = (activeCups / dailyGoal) * 100;
        progressBar.style.width = `${percentage}%`;
        achievementCount.innerText = `${Math.round(percentage)}%`;

        // Update progress text
        if (activeCups === 0) {
            progressText.innerText = "Start your day with a glass of water! 💧";
        } else if (activeCups < 4) {
            progressText.innerText = "Great start! Keep going 🌟";
        } else if (activeCups < 8) {
            progressText.innerText = "Excellent! You're almost there 💪";
        } else {
            progressText.innerText = "Congratulations! Goal achieved 🎉";
            celebrateGoal();
        }
    }

    function saveProgress() {
        localStorage.setItem('waterProgress', activeCups.toString());
        localStorage.setItem('waterProgressDate', new Date().toDateString());
    }

    window.resetWater = function() {
        if (confirm('Are you sure you want to reset your progress?')) {
            activeCups = 0;
            updateWaterUI();
            saveProgress();
        }
    };

    window.completeGoal = function() {
        activeCups = dailyGoal;
        updateWaterUI();
        saveProgress();
    };

    function celebrateGoal() {
        // Simple celebration effect
        const originalText = progressText.innerHTML;
        progressText.innerHTML = "🎉 Amazing! You've reached your daily goal! 🎉";
    }

    // Initialize
    createCups();
});
</script>
@endsection
